import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from './_components/nav'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Jesus Velarde</title>
        <link rel="icon" href="/images/icon.png" />
      </head>
      <body>
        <Navigation />
        {children}
        </body>
    </html>
  )
}
